/*
  SQL Server Script for Batch Delete tons of data 

  [SOME_TABLE] 
  [SOME_INDEX_FIELD]
  [SOME_CONDITION]

*/

DECLARE @BATCHSIZE INT, @WAITFORVAL VARCHAR(8), @ITERATION INT, @TOTALROWS INT, @MAXRUNTIME VARCHAR(8), @MINRUNTIME VARCHAR(8), @BSTOPATMAXTIME BIT, @MSG VARCHAR(500)

IF OBJECT_ID('TEMPDB..#TABLE') IS NULL 
BEGIN
  CREATE TABLE #TABLE
  (
    ID INT
  )
  INSERT INTO #TABLE
  SELECT [SOME_INDEX_FIELD]
  FROM [SOME_TABLE]
  WHERE [SOME_CONDITION] = TRUE
END

SET DEADLOCK_PRIORITY LOW;
SET @BATCHSIZE = 1000
SET @WAITFORVAL = '00:00:00:01'
-- 8AM
SET @MAXRUNTIME = '08:00:00'
-- 6PM
SET @MINRUNTIME = '18:00:00'
-- ENFORCE 8AM STOP TIME
SET @BSTOPATMAXTIME = 0

SET @ITERATION = 0
SET @TOTALROWS = 0

WHILE @BATCHSIZE>0
BEGIN
  IF CONVERT(VARCHAR(8),GETDATE(),108) >= @MAXRUNTIME
    AND CONVERT(VARCHAR(8),GETDATE(),108) <= @MINRUNTIME
    AND @BSTOPATMAXTIME=1
  BEGIN
    RETURN
  END

  WAITFOR DELAY @WAITFORVAL

  DELETE TOP(@BATCHSIZE) 
  FROM [SOME_TABLE] 
  WHERE [SOME_INDEX_FIELD] IN (SELECT TOP(@BATCHSIZE)
    ID
  FROM #TABLE)

  DELETE TOP(@BATCHSIZE) 
  FROM #TABLE

  SET @BATCHSIZE=@@ROWCOUNT
  SET @ITERATION=@ITERATION+1
  SET @TOTALROWS=@TOTALROWS+@BATCHSIZE

  SET @MSG = '['+CONVERT(VARCHAR(8),GETDATE(),108)+'] Iteration: ' + CAST(@ITERATION AS VARCHAR) + ' Total deletes:' + CAST(@TOTALROWS AS VARCHAR)
  RAISERROR (@MSG, 0, 1) WITH NOWAIT
END
